name: 'itential-trigger-automation'
description: 'A JavaScript action to run IAP automation using API trigger'
author: 'Itential'
branding:
  icon: 'activity'
  color: 'blue'
inputs:
  IAP_INSTANCE:
    description: 'IAP Instance to run workflow'
    required: true
  IAP_TOKEN:
    description: 'IAP Instance token to authorize'
    required: true
  API_ENDPOINT:
    description: 'API endpoint name to trigger an automation'
    required: true
  API_ENDPOINT_BODY:
    description: 'the POST body used to create the workflow input'
    required: true
  TIMEOUT:
    description: 'Time interval to check job status'
    default: '15'
  NO_OF_ATTEMPTS:
    description: 'No of attempts to check job status'
    default: '10'
  JOB_STATUS:
    description: 'Display status of the job with the output'
    default: '1'

outputs:
  results: 
    description: 'API Trigger output variables'

runs:
  using: 'node16'
  main: 'dist/index.js'

